### Get all items
GET http://localhost:8000/items?token=demo-token

### Unauthorized
GET http://localhost:8000/items?token=definitely-not-demo-token

### Get item by query
GET http://localhost:8000/items?q=foo&token=demo-token

### Get item by query fails because query is too long
GET http://localhost:8000/items?q=foobar&token=demo-token

### Get item by id
GET http://localhost:8000/items/get_by_id?item_id=foo&token=demo-token



